gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to... whatever this is.\p"
	.string "My name is Kit.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This city’s full of Pokémon.\n"
	.string "We live and work with them,\n"
	.string "sometimes battling each other.\p"
	.string "But even with how close we are, there’s\n"
	.string "still a lot we don’t know about them-\p"
	.string "they’re full of secrets.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Which option are you?\n$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to\n"
	.string "the neighborhood of Sunnyside.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Well...\n"
	.string "Don't come find me.\p"
	.string "$"
